#include <lvgl.h>
#include "screens.h"
#include "screens_compat.h"

/* Creates hidden, zero-size placeholder widgets for the COMPAT STUBS fields
   declared in screens.h. Lets display.c / display_tonex.c keep operating on
   real LVGL objects (just invisible ones) when the EEZ design doesn't supply
   them, instead of dereferencing NULL.

   Hand-maintained — not generated by EEZ Studio. */

static lv_obj_t *make_hidden(lv_obj_t *parent, lv_obj_t *(*ctor)(lv_obj_t *))
{
    lv_obj_t *o = ctor(parent);
    lv_obj_set_size(o, 0, 0);
    lv_obj_add_flag(o, LV_OBJ_FLAG_HIDDEN);
    return o;
}

void screens_compat_init(void)
{
    lv_obj_t *root = objects.screen1;
    if (root == NULL) return;

    objects.ui_skin_image               = make_hidden(root, lv_img_create);
    objects.ui_preset_details_text_area = make_hidden(root, lv_textarea_create);
    objects.ui_entry_keyboard           = make_hidden(root, lv_keyboard_create);
    objects.ui_left_arrow               = make_hidden(root, lv_img_create);
    objects.ui_right_arrow              = make_hidden(root, lv_img_create);
    objects.ui_ok_tick                  = make_hidden(root, lv_img_create);

    objects.ui_chip_gate   = make_hidden(root, lv_obj_create);
    objects.ui_chip_comp   = make_hidden(root, lv_obj_create);
    objects.ui_chip_eq     = make_hidden(root, lv_obj_create);
    objects.ui_chip_amp    = make_hidden(root, lv_obj_create);
    objects.ui_chip_cab    = make_hidden(root, lv_obj_create);
    objects.ui_chip_mod    = make_hidden(root, lv_obj_create);
    objects.ui_chip_delay  = make_hidden(root, lv_obj_create);
    objects.ui_chip_reverb = make_hidden(root, lv_obj_create);
}
